### ISSUE TITLE
ARM64 image not being pulled?

### ISSUE THREAD

**Issue by converseolive** [tenseiken/docker-qbittorrent-wireguard#12]
Hi, i saw a closed issue that was similar, but it seems as though I'm having the same issue,

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

container logs
`exec /bin/bash: exec format error`

Tried the test tag but thats no longer available, running on Rpi 5, docker version 20.10

Cheers

**Comment by tenseiken** [comment]
I think I accidentally re-pushed the linux/amd64 image after building the last one multi-arch and it overwrote the tag on DockerHub with just the linux/amd64 one.  I ran the build again and re-pushed to DockerHub and now I'm seeing both linux/amd64 and linux/arm64 as options. Try it again now.

**Comment by converseolive** [comment]
yep awesome! thats working now, thanks heaps!
