### ISSUE TITLE
No ARM64 image

### ISSUE THREAD

**Issue by ElspethThePict** [tenseiken/docker-qbittorrent-wireguard#2]
I don't know how complicated it would be to get this working on ARM devices like Raspberry Pi, but I figured I'd let you know that I'm getting an error:

`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by tenseiken** [comment]
Good call out. An hour ago I didn't know anything about building multi-arch docker images, and I don't have an arm64 device I can test with. That said, I did take a crack at making one, but it felt a bit easier than it should have been so I probably screwed something up.

Could you help me test? I pushed a new image that _may_ work using the tag "test". You can get it with `docker pull tenseiken/qbittorrent-wireguard:test`

Let me know if it works.

**Comment by ElspethThePict** [comment]
I'm getting a different error now, so it's at least attempting to run which is a good sign!

`Error: IPv6 is disabled on nexthop device.`
Any idea what I need to do here?

**Comment by tenseiken** [comment]
Haven't seen that one. Are you using IPv6 yourself? If not, add this as sysctl for your container: `net.ipv6.conf.all.disable_ipv6=0`

**Comment by ElspethThePict** [comment]
Yes, up and running now!

**Comment by tenseiken** [comment]
Excellent! I'll get the multi-arch image pushed to the :4.6.4 and :latest tags here in a little bit. I'll leave this open for a day or two in case you (or anyone else) runs into a problem with the arm64 image.
