### ISSUE TITLE
Open sourcing Instaloader Docker

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [tenseiken/docker-qbittorrent-wireguard#8]
Hey, 
would you mind open-sourcing your Instaloader Docker image? 
https://hub.docker.com/r/tenseiken/instaloader

Thanks a lot for your work!

**Comment by tenseiken** [comment]
Hey, thanks for the interest. 

I do have it tracked in a private repo, but right now Instaloader itself isn't very reliable. IG has stepped up their scrape detection and you'll probably get your account suspended if you use that image for more than a few minutes. Even slowing it down by adding a long pause in between queries doesn't help. 

I'm not using it currently and don't recommend anyone use it right now. If/when Instaloader gets updated to work more reliably with the new scrape detection, I'll be happy to make that repo public. I am keeping an eye on their releases. 

Now, if you have an idea to improve that situation--outside of substantially modifying the Instaloader code--let me know and I can add you as a collaborator.

**Comment by Lukas-Heiligenbrunner** [comment]
Thats fine for me, thanks for your response :)
