### ISSUE TITLE
Environment variables not being used

### ISSUE THREAD

**Issue by FideliusFalcon** [tenseiken/docker-qbittorrent-wireguard#9]
I'm using the default `docker-compose.yml`, but the environment is not being respected. Even if I set the WEBUI_USER/WEBUI_PASS the username and password is still default. PUID and PGID is also not set correct. I have also tried to remove the config folder.

**Comment by tenseiken** [comment]
I'm not 100% sure if I'm interpreting you right, but the way your comment reads it sounds like you might be expecting WEBUI_USER/WEBUI_PASS to manage the username and password for accessing the web UI. That's not actually the case, but I can understand the confusion--I could have named them better. The values you provide there are used by the script to authenticate with the qBittorrent API to change your listen port to match what the ProtonVPN port forwarding functionality sets it to. More info on the relevant environment variables for ProtonVPN port forwarding can be found starting [here](https://github.com/tenseiken/docker-qbittorrent-wireguard/wiki/Environment-Variables#enableprotonvpnportfwd). If you're not using the ProtonVPN port forwarding functionality, you don't need to set those variables.

Regarding PUID and PGID, what those do is manage the user ID and primary group ID of the user `qbtUser` as it exists inside the container. You can check this by running the following from your host (where containername is the actual name of your container): `docker exec containername id qbtUser`. You should get a line back that shows the UID and GID for qbtUser, and they should match up with what you've passed as environment variables. This user is used to run qbittorrent-nox, so any files it creates (config, cache, actual downloaded data, etc.) will all be created with the same UID and GID. If you use the UID and GID of the user on your host OS that you want to own these files, it will all be done automatically.

So, that's some info about those variables. If that doesn't answer your question, please provide some more detail about the problem you've encountered. Are you having a permissions problem? I'm not sure why you would have deleted /config.

**Comment by 1000Reasons** [comment]
Is it possible to change the qbittorrent web ui credentials?

**Comment by tenseiken** [comment]
Yes, you can do it from the UI itself, in the web UI settings.
